version: '3'

services:
  lambda-hello:
    # TODO build: .
    image: lambci/lambda:python3.8
    volumes:
      # TODO package lambda with serverless (to make it's s_handler.py available)
      - ./function/hello.py:/var/task/function/hello.py:ro,delegated
      # TODO package layer with serverless
      - ./layer/common-code:/opt:ro,delegated
    command: function/hello.hello '{"test":"test"}'
