service: sls-url-shortener
app: serverless-url-shortener
org: toporok

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  versionFunctions: ${strToBool(${param:VERSION_LAMBDAS, 'true'})}

  stage: ${opt:stage, 'dev'}
  region: us-east-1

custom:
  retain-layer-versions: ${strToBool(${param:RETAIN_LAYER_VERSIONS, 'false'})}

package:
  individually: true
  exclude:
    - ./**
  include:
    - LICENSE

layers:
  commonCode:
    name: ${self:service}-${self:provider.stage}-commonCode
    path: layer/common-code
    retain: ${self:custom.retain-layer-versions}
    package:
      include:
        - ./**  # this is relative to layer path

functions:
  hello:
    handler: function/hello.hello
#    module: function
    layers:
      - { Ref: CommonCodeLambdaLayer }
    package:
      include:
        - function/hello.py
